# -*- coding: utf-8 -*-

NEW_STRINGS = {
    # Section Headers & Details Labels
    "contact_and_identification": ("Contact & Identification", "যোগাযোগ ও পরিচয়"),
    "emergency_contact": ("Emergency Contact", "জরুরি যোগাযোগ"),
    "rental_occupancy_history": ("Rental Occupancy History", "ভাড়ার ইতিহাস"),
    "metadata_and_linkage": ("Metadata & Linkage", "নথির তথ্য ও সংযোগ"),
    "financial_balance": ("Financial Balance", "আর্থিক হিসাব"),
    "location_and_description": ("Location & Description", "স্থান ও বিবরণ"),
    "receipt_voucher_section": ("Receipt / Voucher", "রসিদ / ভাউচার"),
    "property_and_rental_unit": ("Property & Rental Unit", "প্রপার্টি ও ইউনিট"),
    "tenant_information_section": ("Tenant Information", "ভাড়াটিয়ার তথ্য"),
    "financial_terms_dates": ("Financial Terms & Dates", "আর্থিক শর্ত ও তারিখ"),
    "meter_consumption_details": ("Meter & Consumption Details", "মিটার ও ব্যবহারের বিবরণ"),
    "property_selection_step": ("1. Property & Tenant Selection", "১. প্রপার্টি ও ভাড়াটিয়া নির্বাচন"),
    "rent_agreement_terms_step": ("2. Rent & Agreement Terms", "২. ভাড়া ও চুক্তির শর্তাবলী"),
    "number_of_floors_label": ("Number of Floors", "মোট তলা"),
    "property_status_label": ("Property Status", "প্রপার্টির অবস্থা"),
    "address_label": ("Address", "ঠিকানা"),
    "units_section_title": ("Units", "ইউনিটসমূহ"),
    "no_units_property_msg": ("No Units Yet\n\nAdd your first unit to this property.", "এখনো কোনো ইউনিট নেই\n\nএই প্রপার্টিতে প্রথম ইউনিট যুক্ত করুন।"),
    "generate_rent_desc": ("Generate monthly rent to calculate dues and collect payments.", "বকেয়া হিসাব ও ভাড়া আদায়ের জন্য মাসিক ভাড়ার রেকর্ড তৈরি করুন।"),
    "waive_remaining_balance_confirm": ("Are you sure you want to waive the remaining balance?", "আপনি কি অবশিষ্ট বকেয়া মওকুফ করতে চান?"),

    # Details Prefixes and Formats
    "prefix_property_id": ("Property ID: %1$s", "প্রপার্টি আইডি: %1$s"),
    "prefix_floors": ("Floors: %1$d", "তলা: %1$d"),
    "prefix_due_date": ("Due Date: %1$s", "পরিশোধের শেষ তারিখ: %1$s"),
    "prefix_bill_number": ("Bill Number: %1$s", "বিল নম্বর: %1$s"),
    "prefix_last_payment": ("Last Payment: %1$s", "সর্বশেষ পরিশোধ: %1$s"),
    "prefix_notes": ("Notes: %1$s", "নোট: %1$s"),
    "prefix_note": ("Note: %1$s", "নোট: %1$s"),
    "prefix_ref": ("Ref: %1$s", "রেফারেন্স: %1$s"),
    "prefix_meter_number": ("Meter Number: %1$s", "মিটার নম্বর: %1$s"),
    "prefix_readings": ("Readings: %1$.1f → %2$.1f (%3$.1f Units)", "রিডিং: %1$.1f → %2$.1f (%3$.1f ইউনিট)"),
    "prefix_rate_per_unit": ("Rate per Unit: %1$s", "প্রতি ইউনিট রেট: %1$s"),
    "prefix_fixed_charge": ("Fixed Charge: %1$s", "নির্দিষ্ট চার্জ: %1$s"),
    "prefix_vat_tax": ("VAT / Tax: %1$s", "ভ্যাট / ট্যাক্স: %1$s"),
    "prefix_units_consumed": ("Units Consumed: %1$.1f", "ব্যবহৃত ইউনিট: %1$.1f"),
    "prefix_units_consumed_zero": ("Units Consumed: 0.0", "ব্যবহৃত ইউনিট: ০.০"),
    "prefix_current_tenant": ("Current Tenant: %1$s", "বর্তমান ভাড়াটিয়া: %1$s"),
    "prefix_tenant_hash": ("Tenant #%1$d", "ভাড়াটিয়া #%1$d"),
    "prefix_unit_hash": ("Unit #%1$d", "ইউনিট #%1$d"),
    "prefix_unit_format": ("Unit %1$s", "ইউনিট %1$s"),
    "prefix_unit_floor_format": ("Unit %1$s (Floor %2$d)", "ইউনিট %1$s (%2$d তলা)"),
    "prefix_unit_floor_type_format": ("Unit %1$s • Floor %2$d • %3$s", "ইউনিট %1$s • %2$d তলা • %3$s"),
    "prefix_deposit_format": ("Deposit: %1$s", "জামানত: %1$s"),
    "prefix_rent_format": ("Rent: %1$s %2$s", "ভাড়া: %1$s %2$s"),
    "prefix_started_format": ("Started: %1$s", "শুরু: %1$s"),
    "prefix_ended_format": ("Ended: %1$s", "সমাপ্ত: %1$s"),
    "prefix_started_ended_format": ("Started: %1$s • Ended: %2$s", "শুরু: %1$s • সমাপ্ত: %2$s"),
    "prefix_paid_format": ("Paid: %1$s", "পরিশোধিত: %1$s"),
    "prefix_due_format": ("Due: %1$s", "বকেয়া: %1$s"),
    "prefix_meter_format": ("Meter: %1$s", "মিটার: %1$s"),
    "prefix_units_summary_format": ("Units: %1$.1f (%2$.1f → %3$.1f)", "ইউনিট: %1$.1f (%2$.1f → %3$.1f)"),
    "prefix_account": ("Account: %1$s", "অ্যাকাউন্ট: %1$s"),
    "prefix_backup_size": ("Backup Size: %1$s", "ব্যাকআপ সাইজ: %1$s"),
    "prefix_error": ("Error: %1$s", "ত্রুটি: %1$s"),
    "prefix_waived_note": ("Waived: %1$s", "মওকুফ: %1$s"),
    "prefix_added_date": ("Added: %1$s", "সংযুক্ত: %1$s"),
    "prefix_size_format": ("Size: %1$s", "সাইজ: %1$s"),

    # Default / Placeholder Values
    "not_set": ("Not set", "নির্ধারিত নয়"),
    "none_value": ("None", "নেই"),
    "no_notes": ("No notes", "কোনো নোট নেই"),
    "no_notes_provided": ("No notes provided", "কোনো নোট দেওয়া হয়নি"),
    "no_description_provided": ("No description provided", "কোনো বিবরণ দেওয়া হয়নি"),
    "present_active": ("Present (Active)", "বর্তমান (চলমান)"),
    "unknown_value": ("Unknown", "অজানা"),
    "this_document": ("this document", "এই ডকুমেন্টটি"),
    "this_expense": ("this expense", "এই খরচটি"),
    "account_not_connected": ("Account: Not connected", "অ্যাকাউন্ট: সংযুক্ত নেই"),
    "connected_label": ("Connected", "সংযুক্ত"),
    "no_backup_yet": ("No backup yet", "এখনো কোনো ব্যাকআপ নেই"),

    # Action / Button Labels
    "select_image_or_pdf": ("+ Select Image or PDF Document", "+ ছবি বা পিডিএফ ডকুমেন্ট নির্বাচন করুন"),
    "attach_image_or_pdf": ("+ Attach Image / PDF", "+ ছবি / পিডিএফ যুক্ত করুন"),
    "add_unit_button": ("+ Add Unit", "+ ইউনিট যুক্ত করুন"),
    "view_tenant_profile": ("👤 View Tenant Profile", "👤 ভাড়াটিয়ার প্রোফাইল দেখুন"),
    "save_property": ("Save Property", "প্রপার্টি সংরক্ষণ করুন"),
    "update_property": ("Update Property", "প্রপার্টি আপডেট করুন"),
    "save_unit": ("Save Unit", "ইউনিট সংরক্ষণ করুন"),
    "update_unit": ("Update Unit", "ইউনিট আপডেট করুন"),
    "copy_sha1": ("Copy SHA-1", "SHA-1 কপি করুন"),

    # Form Hints
    "hint_property_name_req": ("Property Name *", "প্রপার্টির নাম *"),
    "hint_property_address_req": ("Address *", "ঠিকানা *"),
    "hint_property_type": ("Property Type", "প্রপার্টির ধরন"),
    "hint_property_floors": ("Number of Floors", "মোট তলা"),
    "hint_property_notes": ("Notes", "নোট"),
    "hint_unit_number_req": ("Unit Number *", "ইউনিট নম্বর *"),
    "hint_unit_floor": ("Floor", "তলা"),
    "hint_unit_type": ("Unit Type", "ইউনিটের ধরন"),
    "hint_unit_rent_req": ("Monthly Rent *", "মাসিক ভাড়া *"),
    "hint_unit_deposit": ("Security Deposit", "জামানত"),
    "hint_unit_status": ("Status", "অবস্থা"),
    "hint_expense_desc_example": ("Description (e.g. Electrical wiring repair)", "বিবরণ (যেমন: বৈদ্যুতিক তার মেরামত)"),
    "hint_tenant_name_req": ("Full Name *", "সম্পূর্ণ নাম *"),
    "hint_phone_req": ("Phone Number *", "ফোন নম্বর *"),

    # Plural / Count Formats
    "count_properties_singular": ("%1$d Property", "%1$d টি প্রপার্টি"),
    "count_properties_plural": ("%1$d Properties", "%1$d টি প্রপার্টি"),
    "count_units_singular": ("%1$d Unit", "%1$d টি ইউনিট"),
    "count_units_plural": ("%1$d Units", "%1$d টি ইউনিট"),
    "count_tenants_singular": ("%1$d Tenant", "%1$d জন ভাড়াটিয়া"),
    "count_tenants_plural": ("%1$d Tenants", "%1$d জন ভাড়াটিয়া"),
    "count_tenancies_singular": ("%1$d Tenancy", "%1$d টি চুক্তি"),
    "count_tenancies_plural": ("%1$d Tenancies", "%1$d টি চুক্তি"),
    "count_rent_records_singular": ("%1$d Rent Record", "%1$d টি ভাড়ার হিসাব"),
    "count_rent_records_plural": ("%1$d Rent Records", "%1$d টি ভাড়ার হিসাব"),
    "count_utility_bills_singular": ("%1$d Utility Bill", "%1$d টি ইউটিলিটি বিল"),
    "count_utility_bills_plural": ("%1$d Utility Bills", "%1$d টি ইউটিলিটি বিল"),
    "count_expenses_singular": ("%1$d Expense", "%1$d টি খরচ"),
    "count_expenses_plural": ("%1$d Expenses", "%1$d টি খরচ"),
    "count_documents_singular": ("%1$d Document", "%1$d টি ডকুমেন্ট"),
    "count_documents_plural": ("%1$d Documents", "%1$d টি ডকুমেন্ট"),
    "count_records_singular": ("%1$d record", "%1$d টি রেকর্ড"),
    "count_records_plural": ("%1$d records", "%1$d টি রেকর্ড"),

    # Property Types Display
    "prop_type_apartment_building": ("Apartment Building", "অ্যাপার্টমেন্ট বিল্ডিং"),
    "prop_type_house": ("House", "আবাসিক বাড়ি"),
    "prop_type_duplex": ("Duplex", "ডুপ্লেক্স"),
    "prop_type_commercial": ("Commercial Building", "বাণিজ্যিক ভবন"),
    "prop_type_shop": ("Shop", "দোকান"),
    "prop_type_office": ("Office", "অফিস"),
    "prop_type_other": ("Other", "অন্যান্য"),

    # Unit Types Display
    "unit_type_apartment": ("Apartment", "অ্যাপার্টমেন্ট"),
    "unit_type_flat": ("Flat", "ফ্ল্যাট"),
    "unit_type_room": ("Room", "রুম"),
    "unit_type_shop": ("Shop", "দোকান"),
    "unit_type_office": ("Office", "অফিস"),
    "unit_type_parking": ("Parking", "গ্যারেজ/পার্কিং"),
    "unit_type_other": ("Other", "অন্যান্য"),

    # Payment Methods Display
    "payment_method_cash": ("Cash", "নগদ"),
    "payment_method_bank_transfer": ("Bank Transfer", "ব্যাংক ট্রান্সফার"),
    "payment_method_mobile_banking": ("Mobile Banking", "মোবাইল ব্যাংকিং (বিকাশ/নগদ)"),
    "payment_method_card": ("Card", "কার্ড"),
    "payment_method_cheque": ("Cheque", "চেক"),
    "payment_method_other": ("Other", "অন্যান্য"),

    # Bill Meter Titles
    "meter_section_electricity": ("⚡ Electricity Meter & Consumption Details", "⚡ বিদ্যুৎ মিটার ও ব্যবহারের বিবরণ"),
    "meter_section_water": ("💧 Water Meter Details (Optional)", "💧 পানি মিটার বিবরণ (ঐচ্ছিক)"),
    "meter_section_gas": ("🔥 Gas Meter Details (Optional)", "🔥 গ্যাস মিটার বিবরণ (ঐচ্ছিক)"),

    # Additional Validation and Toast Messages
    "billing_month_required": ("Billing month is required", "বিলিং মাস আবশ্যক"),
    "due_date_required": ("Due date is required", "পরিশোধের শেষ তারিখ আবশ্যক"),
    "expense_date_required": ("Expense date is required", "খরচের তারিখ আবশ্যক"),
    "property_name_required": ("Property name is required", "প্রপার্টির নাম আবশ্যক"),
    "address_required": ("Address is required", "ঠিকানা আবশ্যক"),
    "valid_number_required": ("Enter a valid number", "সঠিক সংখ্যা লিখুন"),
    "update_failed": ("Update failed", "আপডেট ব্যর্থ হয়েছে"),
    "save_failed": ("Save failed", "সংরক্ষণ ব্যর্থ হয়েছে"),
    "unable_to_load_properties": ("Unable to load properties", "প্রপার্টি লোড করা যায়নি"),
    "end_date_before_start_error": ("End date cannot be before start date", "সমাপ্তির তারিখ শুরুর তারিখের আগের হতে পারে না"),
    "unit_already_occupied_error": ("Unit is already occupied", "এই ইউনিটটি ইতোমধ্যে ভাড়া দেওয়া আছে"),
    "duplicate_bill_error_msg": ("A %1$s bill for %2$s already exists for this property/unit.", "এই প্রপার্টি/ইউনিটের জন্য %2$s মাসের %1$s বিল ইতোমধ্যে বিদ্যমান।"),
    "expense_amount_min_error": ("Expense amount must be greater than zero", "খরচের পরিমাণ শূন্যের বেশি হতে হবে"),
    "payment_amount_min_error": ("Payment amount must be greater than zero", "পরিশোধের পরিমাণ শূন্যের বেশি হতে হবে"),
    "payment_amount_exceeds_error": ("Payment amount exceeds remaining balance", "পরিশোধের পরিমাণ বকেয়া পরিমাণের বেশি হতে পারে না"),
    "rent_record_not_found": ("Rent record not found", "ভাড়ার রেকর্ড পাওয়া যায়নি"),
    "utility_bill_not_found": ("Utility bill not found", "ইউটিলিটি বিল পাওয়া যায়নি"),
    "unit_not_found": ("Unit not found", "ইউনিট পাওয়া যায়নি"),

    # Filter Options
    "filter_all": ("All", "সব"),
    "filter_active": ("Active", "সক্রিয়"),
    "filter_inactive": ("Inactive", "নিষ্ক্রিয়"),
    "filter_archived": ("Archived", "আর্কাইভ"),
    "filter_vacant": ("Vacant", "খালি"),
    "filter_occupied": ("Occupied", "ভাড়া দেওয়া"),
    "filter_reserved": ("Reserved", "সংরক্ষিত"),
    "filter_maintenance": ("Maintenance", "মেরামত চলছে"),
    "filter_unpaid": ("Unpaid", "বকেয়া"),
    "filter_partial": ("Partial", "আংশিক"),
    "filter_paid": ("Paid", "পরিশোধিত"),
    "filter_overdue": ("Overdue", "মেয়াদোত্তীর্ণ"),
    "filter_waived": ("Waived", "মওকুফ"),
    "filter_ended": ("Ended", "সমাপ্ত"),
    "filter_cancelled": ("Cancelled", "বাতিল"),
    "filter_electricity": ("Electricity", "বিদ্যুৎ"),
    "filter_water": ("Water", "পানি"),
    "filter_gas": ("Gas", "গ্যাস"),
    "filter_internet": ("Internet", "ইন্টারনেট"),
    "filter_other": ("Other", "অন্যান্য"),
    "filter_repair": ("Repair", "মেরামত"),
    "filter_cleaning": ("Cleaning", "পরিষ্কার"),
    "filter_security": ("Security", "নিরাপত্তা"),
    "filter_property_tax": ("Property Tax", "হোল্ডিং ট্যাক্স"),
}

print(f"Total new string resources to add: {len(NEW_STRINGS)}")
