# -*- coding: utf-8 -*-
import os
import re

RES_DIR = r"d:\My Apps Creations\RobHouseRental\app\src\main\res\layout"

# Exact replacements for layouts
REPLACEMENTS = {
    # Headers & Hints & Buttons
    'android:title="Add Property"': 'android:title="@string/add_property_title"',
    'android:hint="Property Name *"': 'android:hint="@string/hint_property_name_req"',
    'android:hint="Address *"': 'android:hint="@string/hint_property_address_req"',
    'android:hint="Property Type"': 'android:hint="@string/hint_property_type"',
    'android:hint="Number of Floors"': 'android:hint="@string/hint_property_floors"',
    'android:hint="Notes"': 'android:hint="@string/hint_property_notes"',
    'android:text="Save Property"': 'android:text="@string/save_property"',
    'android:title="Add Unit"': 'android:title="@string/add_unit_title"',
    'android:hint="Unit Number *"': 'android:hint="@string/hint_unit_number_req"',
    'android:hint="Floor"': 'android:hint="@string/hint_unit_floor"',
    'android:hint="Unit Type"': 'android:hint="@string/hint_unit_type"',
    'android:hint="Monthly Rent *"': 'android:hint="@string/hint_unit_rent_req"',
    'android:hint="Security Deposit"': 'android:hint="@string/hint_unit_deposit"',
    'android:hint="Status"': 'android:hint="@string/hint_unit_status"',
    'android:text="Save Unit"': 'android:text="@string/save_unit"',
    'android:hint="Description (e.g. Electrical wiring repair)"': 'android:hint="@string/hint_expense_desc_example"',
    'android:text="+ Select Image or PDF Document"': 'android:text="@string/select_image_or_pdf"',
    'android:text="+ Attach Image / PDF"': 'android:text="@string/attach_image_or_pdf"',
    'android:text="1. Property &amp; Tenant Selection"': 'android:text="@string/property_selection_step"',
    'android:text="2. Rent &amp; Agreement Terms"': 'android:text="@string/rent_agreement_terms_step"',
    'android:text="Are you sure you want to waive the remaining balance?"': 'android:text="@string/waive_remaining_balance_confirm"',
    'android:text="👤  View Tenant Profile"': 'android:text="@string/view_tenant_profile"',
    'android:text="+ Add Unit"': 'android:text="@string/add_unit_button"',
    'android:text="Edit Property"': 'android:text="@string/edit_property"',
    'android:title="Properties"': 'android:title="@string/properties_title"',
    'android:title="Property Details"': 'android:title="@string/property_details_title"',
    'android:text="No Properties Yet"': 'android:text="@string/no_properties_found"',
    'android:text="Add your first property to get started."': 'android:text="@string/add_property_to_get_started"',
    'android:text="Add Property"': 'android:text="@string/add_property"',

    'android:text="Address"': 'android:text="@string/address_label"',
    'android:text="Property Type"': 'android:text="@string/property_type"',
    'android:text="Number of Floors"': 'android:text="@string/number_of_floors_label"',
    'android:text="Notes"': 'android:text="@string/notes"',
    'android:text="Property Status"': 'android:text="@string/property_status_label"',
    'android:text="Units"': 'android:text="@string/units_section_title"',
    'android:text="No Units Yet&#10;&#10;Add your first unit to this property."': 'android:text="@string/no_units_property_msg"',
    'android:text="Contact &amp; Identification"': 'android:text="@string/contact_and_identification"',
    'android:text="Emergency Contact"': 'android:text="@string/emergency_contact"',
    'android:text="Rental Occupancy History"': 'android:text="@string/rental_occupancy_history"',
    'android:text="Property &amp; Rental Unit"': 'android:text="@string/property_and_rental_unit"',
    'android:text="Tenant Information"': 'android:text="@string/tenant_information_section"',
    'android:text="Financial Terms &amp; Dates"': 'android:text="@string/financial_terms_dates"',
    'android:text="Financial Balance"': 'android:text="@string/financial_balance"',
    'android:text="⚡ Meter &amp; Consumption Details"': 'android:text="@string/meter_consumption_details"',
    'android:text="Location &amp; Description"': 'android:text="@string/location_and_description"',
    'android:text="Receipt / Voucher"': 'android:text="@string/receipt_voucher_section"',
    'android:text="Metadata &amp; Linkage"': 'android:text="@string/metadata_and_linkage"',
    'android:text="Document File"': 'android:text="@string/doc_type_general"',
    'android:text="Total Documents"': 'android:text="@string/total_documents"',
    'android:text="Total Count"': 'android:text="@string/total_expenses"',
    'android:text="Latest Cloud Backup"': 'android:text="@string/latest_cloud_backup"',
    'android:text="Generate monthly rent to calculate dues and collect payments."': 'android:text="@string/generate_rent_desc"',
}

# Dynamic placeholder text to strip (set to empty string)
PLACEHOLDERS_TO_REMOVE = [
    'android:text="Green View Building"',
    'android:text="Uttara, Dhaka, Bangladesh"',
    'android:text="Dhaka, Bangladesh"',
    'android:text="Apartment Building"',
    'android:text="Main rental property"',
    'android:text="Active"',
    'android:text="ACTIVE"',
    'android:text="Property ID: 1"',
    'android:text="0 Properties"',
    'android:text="0 Units"',
    'android:text="0 Tenants"',
    'android:text="0 Tenancies"',
    'android:text="0 Rent Records"',
    'android:text="0 Utility Bills"',
    'android:text="0 Expenses"',
    'android:text="0 Documents"',
    'android:text="0 records"',
    'android:text="Rahim Ahmed"',
    'android:text="017XXXXXXXX"',
    'android:text="01712345678"',
    'android:text="1990123456789"',
    'android:text="None"',
    'android:text="No notes"',
    'android:text="Not set"',
    'android:text="Present (Active)"',
    'android:text="৳15,000 / month"',
    'android:text="Deposit: ৳30,000"',
    'android:text="Unit 101 • Floor 1 • 2 BHK"',
    'android:text="Green View Apartment"',
    'android:text="Green View Apartment • Unit 101"',
    'android:text="01 Aug 2026"',
    'android:text="08 Aug 2026"',
    'android:text="10 Aug 2026"',
    'android:text="15 Aug 2026"',
    'android:text="August 2026"',
    'android:text="UNPAID"',
    'android:text="Due Date: 10 Aug 2026"',
    'android:text="Due Date: 15 Aug 2026"',
    'android:text="Bill Number: INV-2026-001"',
    'android:text="Last Payment: None"',
    'android:text="Notes: None"',
    'android:text="Meter Number: MET-88392"',
    'android:text="Readings: 1240.0 → 1380.0 (140.0 Units)"',
    'android:text="Rate per Unit: ৳9.50"',
    'android:text="Fixed Charge: ৳50.00"',
    'android:text="VAT / Tax: ৳70.00"',
    'android:text="Units Consumed: 0.0"',
    'android:text="👤 Current Tenant: Rahim Ahmed"',
    'android:text="👤 Tenant: Rahim Ahmed"',
    'android:text="👤 Rahim Ahmed"',
    'android:text="Electricity Bill"',
    'android:text="Tenant NID Copy"',
    'android:text="Tenant NID Front &amp; Back"',
    'android:text="National ID (NID)"',
    'android:text="National ID"',
    'android:text="NID Front and Back"',
    'android:text="title_deed.pdf"',
    'android:text="1.4 MB • PDF"',
    'android:text="doc_1773099238.pdf"',
    'android:text="receipt_voucher.pdf"',
    'android:text="voucher_receipt.jpg"',
    'android:text="Electrical Repair"',
    'android:text="📅 10 Aug 2026"',
    'android:text="📅 15 Aug 2026"',
    'android:text="📅 August 2026"',
    'android:text="📅 August 2026 • Due: 15 Aug 2026"',
    'android:text="📅 09 Aug 2026, 01:00 AM"',
    'android:text="💾 1.2 MB"',
    'android:text="💾 25.4 MB"',
    'android:text="💾 Size: 1.4 MB • PDF Document"',
    'android:text="📅 Added: 10 Aug 2026"',
    'android:text="Notes: Verified original NID card."',
    'android:text="Wiring and circuit breaker replacement in master bedroom."',
    'android:text="Note: Paid in cash to technician."',
    'android:text="Note: Paid via bKash"',
    'android:text="Ref: TrxID #88219"',
    'android:text="Ref: TrxID #99212"',
    'android:text="📎 Voucher"',
    'android:text="PDF"',
    'android:text="Manual Backup"',
    'android:text="SUCCESS"',
    'android:text="Due: 10 Aug 2026"',
    'android:text="Rent: ৳15,000 / month"',
    'android:text="Started: 01 Aug 2026"',
    'android:text="AGR-001"',
    'android:text="📞 01712345678"',
    'android:text="Occupation: Engineer"',
    'android:text="NID: 1990123456789"',
    'android:text="Unit 101"',
    'android:text="VACANT"',
    'android:text="Floor 1 • Apartment"',
    'android:text="Notes..."',
    'android:text="Units: 140.0 (1240 → 1380)"',
    'android:text="Account: Not connected"',
    'android:text="No backup yet"',
    'android:text="NONE"',
    'android:text="Backup Size: 0 MB"',
    'android:text="Cash"',
    'android:text="Floors: 5"',
    'android:text="🏢 Green View Apartment • 👤 Rahim Ahmed"',
    'android:text="🏢 Green View Apartment • Unit 101"',
]

updated_count = 0
for f in os.listdir(RES_DIR):
    if f.endswith(".xml"):
        path = os.path.join(RES_DIR, f)
        with open(path, "r", encoding="utf-8") as file:
            content = file.read()
        
        orig = content
        for k, v in REPLACEMENTS.items():
            content = content.replace(k, v)
        for p in PLACEHOLDERS_TO_REMOVE:
            content = content.replace(p, "")
        
        if content != orig:
            with open(path, "w", encoding="utf-8") as file:
                file.write(content)
            updated_count += 1
            print(f"Updated {f}")

print(f"Total XML layout files updated: {updated_count}")
